### ISSUE TITLE
replace flask with sanic

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-sdk#109]
We should replace Flask with Sanic in the `rasa-sdk` so that we have a consistent stack across our projects. Based on the discussion here: https://github.com/RasaHQ/customers/issues/164#issuecomment-544596980

**Comment by cowjen01** [comment]
We are currently finishing a project based on the action server and we've run into the problem with asynchronous responding to new requests if any of previous one sleeps. Accidentally we've found out this issue like 5 days before project release when we were running some tests. We would love to help to replace Flask by Sanic because if not so, we can't run the chatbot in production environment.

**Comment by akelad** [comment]
@cowjen01 what kind of actions are you running that this is an issue? We'd also be happy to accept a PR if you're already working on this

**Comment by cowjen01** [comment]
@akelad The problem is Flash dos not support async handling and sending of requests, so if any of requests delay other has to wait until it's completed. We build simple chatbot for audience of 10.000 possible users so it's unimaginable to respond in reasonable time if i/o calls are executed asynchronously. Yesterday we've started to work on this replacement and in 2-3 days we are going to make a PR.

**Comment by akelad** [comment]
got it, that makes sense. And that's great, looking forward to your PR!

**Comment by cowjen01** [comment]
#113

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa-sdk/pull/113
