### ISSUE TITLE
Choosing requested slot from database

### ISSUE THREAD

**Issue by EdukondaluK** [RasaHQ/rasa-sdk#179]
**Description of Problem**:

In form action, required_slots values are not able to extract from database.
**Overview of the Solution**:

form action,required slots values are getting from text , from intent etc..
not from existing database values.
**Examples** (if relevant):

suppose chat query like  what is the contact of vendor 
normal slot : vendor
then requested slot location
Bot) which location of  contact you want  
reply through buttons and it will be dynamic 
 buttons: should come data from database.
      1) India
      2) Us
    etc.. it should come dynamically from database
**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hi @EdukondaluK, you can do this by overwriting the `required_slots()` function, by querying the database from there. You can even make the required_slots dynamic/conditional on something. Eg. like described here: https://rasa.com/docs/rasa/core/forms/#handling-conditional-slot-logic

Since this is a usage quesiton, rather than an enhancement, please post any further questions you have on our community [forum](https://forum.rasa.com)
