### ISSUE TITLE
FormAction from_text not_intent confidence threshold

### ISSUE THREAD

**Issue by ValeKnappich** [RasaHQ/rasa-sdk#256]
**Description of Problem**:

When a ```FormAction``` fills a slot from free text, the ```slot_mapping``` function lets you define intents for which the filling is done (```intent``` keyword) or not done (```not_intent``` keyword). 

For example if you want rasa to fill a slot with a free text, unless the user wants to abort the process, you might define your slot mappings as follows:
```python
def slot_mappings ( self ) -> Dict [ Text , Union [ Dict , List [ Dict ]]]:
   return {
      "my_slot": [self .from_text(not_intent =["abort"])]
   }
```

Since confidence is likely to be low on free text, it might happen that the ```abort``` intent is falsely classified with lets say a confidence of 0.3. This leads to unwanted behaviour.

**Overview of the Solution**:

A solution would be to provide a confidence threshold, that constraints the ```not_intent``` constraint. For example:
```python
def slot_mappings ( self ) -> Dict [ Text , Union [ Dict , List [ Dict ]]]:
   return {
      "my_slot": [self .from_text(not_intent =[("abort", 0.6)])]
   }
```
Where 0.6 would be the minimal confidence under which the constraint is used. 

I'm not very familiar with the implementation of ```slot_mappings``` but I imagine the solution is rather easy.

I searched for similar issues and was surprised not to find any. Feel free to mark this as duplicate if I missed one.
If not, it would be great if someone with more knowledge about the implementation could provide a sample adjustment to the ```slot_mappings``` implementation.
Thanks.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hey @ValeKnappich thanks for the suggestion, that brought up a good discussion in our team. With the 2.0 release coming up, there's a new way of handling an NLU fallback, where the intent gets overriden with the `nlu_fallback` intent. We think that the confidence threshold within a form should be handled on a fallback level. So you can handle it by specifying `not_intent=nlu_fallback` in the slot_mapping. We're also considering making this a global setting within the form, so that if you want that behaviour, you don't have to specify it for every slot_mapping. 
I'm going to close this issue in favour of this new one #261 , let me know if you have any thoughts or questions.

**Comment by ValeKnappich** [comment]
Hi @akelad thanks, that sounds great.
The only second thought I have is, that this approach provides less granularity than my proposal. When you have a second intent that interrupts the form, one might argue that the threshold should depend on how critical the resulting action is. If the second intent would e.g. be a question, it could make sense to interrupt the form for an abortion only on high confidence whereas the question answering could be performed even on lower confidence. 
Anyway your solution is definitely more elegant, yet less granular. How relevant this granularity is and how this would fit into your plans for rasa 2.0 remains to be discussed.

**Comment by akelad** [comment]
You can still define `not_intent=nlu_fallback` on a slot level, the global setting is only designed in case you want this to be the behaviour for **every slot**. I think allowing the confidence threshold to be that granular isn't the right way to do things, because whether it's a confidence of 0.3 or 0.5, that probably doesn't really make a difference
