### ISSUE TITLE
add activation function in forms

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-sdk#80]
The idea is that we would add an activation function where any actions that need to be performed before the form starts go. Then we would maybe also want to reinforce that forms should be called directly after inputs (e.g. by checking stories and tellling people to put anything that came before the form action in their activation function to avoid undesired behavior like slots from activating input not filling)

**Comment by wochinge** [comment]
@erohmensing What would these actions do?

**Comment by erohmensing** [comment]
they could do even simple things such as utterances -- the main issue is that if you add a different action before the form action, requested slots filled from the user input (that aren't auto-filled into slots) are not validated correctly. i was of the opinion that that was a bug, but @Ghostvv suggested doing it this way instead. thread: https://github.com/RasaHQ/rasa/issues/3279#issuecomment-485684005

i.e. minimum reproducible: something like
```
*subscribe_newsletter{"email":"ella@ella.ella"} 
          - utter_can_do
          - subscribe_newsletter_form
```
with `autofill:false` and a validation method that e.g. says "reject it if it includes `ella`" won't reject it

**Comment by yangjianxin1** [comment]
I can not agree more with you，when I ask "What is the weather like in Beijing"，I prefer that the chatbot would fill the slot "weather_city" immediately，rather than doing nothing。This question has confused me for a long time。Now I know that we can rewrite _activate_if_required() to implement this goal.

**Comment by yangjianxin1** [comment]
@erohmensing I can not agree more with you，when I ask "What is the weather like in Beijing"，I prefer that the chatbot would fill the slot "weather_city" immediately，rather than doing nothing。This question has confused me for a long time。Now I know that we can rewrite _activate_if_required() to implement this goal.

**Comment by wochinge** [comment]
I deprio this for now since their might be bigger changes to forms in the near future

**Comment by wochinge** [comment]
@Ghostvv 

> the main issue is that if you add a different action before the form action, requested slots filled from the user input (that aren't auto-filled into slots) are not validated correctly.

This is no longer true and we can close it, correct?

**Comment by Ghostvv** [comment]
not for sdk, one line needs to be changed there
